### ISSUE TITLE
How to use Store State from another Feature Module?

### ISSUE THREAD

**Issue by bhaidar** [BioPhoton/angular-ngrx-refactoring#7]
Hello,
Any idea on how to access the State inside a Store from another Feature module?

Thanks

**Comment by BioPhoton** [comment]
I don't understand?
You can just select it over the store obj. `this.store.select(console.log);`

I create a branch for u to show that this is very easy:
https://github.com/BioPhoton/angular-ngrx-refactoring/blob/accessing-store-from-other-feature/src/app/pages/airport/components/search/search.component.ts#L18-L21

**Comment by bhaidar** [comment]
Thanks @BioPhoton for the branch. 
I am just confused with the state stored on the root and those on features. But from what I can see from your code, even the feature state has to be placed in the root state. So I can access anything anywhere!
